name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repo name
        id: set-repo-name
        run: echo "repo_name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ steps.set-repo-name.outputs.repo_name }}:latest

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy to Proxmox
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            # Install jq (for parsing API responses)
            sudo apt update
            sudo apt install jq -y

            # Get API Token Secret
            TOKEN_SECRET=$(pvesh get /access/token --output-format json | jq -r '.data[] | select(.userid == "${{ secrets.API_TOKEN_ID }}") | .tokenid')

            # Stop and destroy any existing container
            qm stop ${{ secrets.VM_ID }} || true
            qm destroy ${{ secrets.VM_ID }} || true

            # Create a new container from template
            qm create ${{ secrets.VM_ID }} --clone ${{ secrets.TEMPLATE_ID }} --name badgey --net0 virtio,bridge=vmbr1,ip=10.10.10.20/24
            qm set ${{ secrets.VM_ID }} --description "Updated by GitHub Actions: \$(date)"

            # Bind mount the database file
            qm set ${{ secrets.VM_ID }} --hostpci0 /opt/badgey/data/db.sqlite,/usr/src/app/db/db.sqlite

            # Set environment variables
            qm set ${{ secrets.VM_ID }} --env GEMINI_API=${GEMINI_API},TOKEN=${TOKEN}

            # Start the container
            qm start ${{ secrets.VM_ID }}

            # Wait for the container to be ready
            sleep 30

            # Pull the latest image and run it in the container using the new token secret
            curl -k -s -X POST \
            https://${{ secrets.SSH_HOST }}:8006/api2/json/nodes/razor/lxc/${{ secrets.VM_ID }}/execute \
            -H "Authorization: PVEAPIToken=${{ secrets.API_TOKEN_ID }}=${TOKEN_SECRET}" \
            -d command="docker" \
            -d command="pull" \
            -d command="ghcr.io/${{ steps.set-repo-name.outputs.repo_name }}:latest"

            qm exec ${{ secrets.VM_ID }} docker run -d --restart=always --name badgey-app ghcr.io/${{ steps.set-repo-name.outputs.repo_name }}:latest

          EOF
        env:
          GEMINI_API: ${{ secrets.GEMINI_API }}
          TOKEN: ${{ secrets.TOKEN }}